Repository team-chang-ppo/location_tracking_module_backend, pull requests merged in 2024-05, with the labels that each got.

#26 perf : Write Back 패턴을 적용한 캐싱 도입
  services/tracking/tracking_server/build.gradle
  services/tracking/tracking_server/load-test/__pycache__/locustfile-test.cpython-311.pyc
  services/tracking/tracking_server/load-test/__pycache__/locustfile-tracking-cache.cpython-311.pyc
  services/tracking/tracking_server/load-test/docker-compose.yml
  services/tracking/tracking_server/load-test/locustfile-tracking-cache.py
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/api/TrackingController.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/api/request/GenerateTokenRequest.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/api/request/StartTrackingRequest.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/api/request/TrackingRequest.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/api/response/TrackingResponse.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/api/validation/ValidPoint.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/api/validation/ValidPointValidator.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/config/AsyncConfig.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/config/CacheConfig.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/config/RedisConfig.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/domain/Coordinates.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/domain/mongodb/Coordinates.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/domain/mongodb/Scope.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/domain/mongodb/Tracking.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/domain/redis/CoordinateRedisEntity.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/domain/redis/TrackingRedisEntity.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/exception/common/ErrorCode.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/repository/CoordinatesRepository.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/repository/RedisRepository.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/repository/TrackingRepository.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/service/AsyncService.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/service/TrackingCacheService.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/service/TrackingService.java
  services/tracking/tracking_server/src/main/java/org/changppo/tracking/util/RetryUtil.java
  services/tracking/tracking_server/src/test/java/org/changppo/tracking/api/TrackingControllerTest.java
  services/tracking/tracking_server/src/test/java/org/changppo/tracking/repository/CoordinatesRepositoryTest.java
Labels: perf, refactor

#37 feat : Github 계정으로 로그인을 지원
  services/account/account_core/account_domain/src/main/generated/org/changppo/account/entity/member/QMemberRoleId.java
  services/account/account_core/account_domain/src/main/generated/org/changppo/account/entity/member/oauth2/QOAuth2AuthorizedClient.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/entity/member/MemberRoleId.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/entity/member/oauth2/OAuth2AuthorizedClient.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/entity/member/oauth2/OAuth2AuthorizedClientId.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/repository/member/oauth2/OAuth2AuthorizedClientRepository.java
  services/account/account_core/account_infra/src/main/java/org/changppo/account/oauth2/OAuth2Client.java
  services/account/account_core/account_infra/src/main/java/org/changppo/account/oauth2/OAuth2Properties.java
  services/account/account_core/account_infra/src/main/java/org/changppo/account/oauth2/github/GitHubConstants.java
  services/account/account_core/account_infra/src/main/java/org/changppo/account/oauth2/github/GitHubOAuth2Client.java
  services/account/account_server-api/src/main/java/org/changppo/account/security/oauth2/CustomOAuth2UserService.java
  services/account/account_server-api/src/main/java/org/changppo/account/security/oauth2/response/GitHubResponse.java
  services/account/account_server-api/src/main/java/org/changppo/account/security/oauth2/response/KakaoResponse.java
  services/account/account_server-api/src/main/java/org/changppo/account/security/oauth2/response/OAuth2Response.java
  services/account/account_server-api/src/main/java/org/changppo/account/security/oauth2/response/OAuth2ResponseFactory.java
  services/account/account_server-api/src/main/resources/sql/init_domain_database.sql
  services/account/account_server-batch/src/main/java/org/changppo/account/batch/job/WriterConfig.java
  services/account/account_server-batch/src/test/java/org/changppo/account/DatabaseCleaner.java
  services/account/account_server-batch/src/test/java/org/changppo/account/TestInitDB.java
  services/account/account_utils/src/main/java/org/changppo/account/type/OAuth2Type.java
Labels: feature

#39 Querydsl을 이용한 Dao계층 리팩토링
  services/account/account_core/account_domain/src/main/generated/org/changppo/account/service/dto/apikey/QApiKeyDto.java
  services/account/account_core/account_domain/src/main/generated/org/changppo/account/service/dto/card/QCardDto.java
  services/account/account_core/account_domain/src/main/generated/org/changppo/account/service/dto/member/QMemberDto.java
  services/account/account_core/account_domain/src/main/generated/org/changppo/account/service/dto/payment/QPaymentDto.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/config/QuerydslConfig.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/repository/apikey/ApiKeyRepository.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/repository/apikey/ApiKeyRepositoryImpl.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/repository/apikey/QuerydslApiKeyRepository.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/repository/card/CardRepository.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/repository/card/CardRepositoryImpl.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/repository/card/QuerydslCardRepository.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/repository/member/MemberRepository.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/repository/member/MemberRepositoryImpl.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/repository/member/QuerydslMemberRepository.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/repository/payment/PaymentRepository.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/repository/payment/PaymentRepositoryImpl.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/repository/payment/QuerydslPaymentRepository.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/service/dto/apikey/ApiKeyDto.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/service/dto/card/CardDto.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/service/dto/member/MemberDto.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/service/dto/payment/PaymentDto.java
  services/account/account_server-api/src/main/java/org/changppo/account/service/card/CardService.java
  services/account/account_server-batch/src/main/java/org/changppo/account/batch/job/JobConfig.java
  services/account/account_server-batch/src/main/java/org/changppo/account/batch/job/WriterConfig.java
  services/account/account_server-batch/src/test/java/org/changppo/account/job/AutomaticPaymentExecutionJobTest.java
Labels: feature, refactor

#41 feat : JWT 로직, Response Body 등 프로젝트 공용에서 사용되는 로직 모듈화
  services/account/account_server-api/build.gradle
  services/account/account_server-api/src/main/java/org/changppo/account/config/JwtConfig.java
  services/account/account_server-api/src/main/java/org/changppo/account/controller/apikey/ApiKeyController.java
  services/account/account_server-api/src/main/java/org/changppo/account/controller/auth/LoginFailureController.java
  services/account/account_server-api/src/main/java/org/changppo/account/controller/auth/LoginSuccessController.java
  services/account/account_server-api/src/main/java/org/changppo/account/controller/card/CardController.java
  services/account/account_server-api/src/main/java/org/changppo/account/controller/card/paymentgateway/kakaopay/KakaopayCardController.java
  services/account/account_server-api/src/main/java/org/changppo/account/controller/member/MemberController.java
  services/account/account_server-api/src/main/java/org/changppo/account/controller/payment/PaymentController.java
  services/account/account_server-api/src/main/java/org/changppo/account/response/Result.java
  services/account/account_server-api/src/main/java/org/changppo/account/response/exception/common/ExceptionAdvice.java
  services/account/account_server-api/src/main/java/org/changppo/account/response/exception/common/ResponseHandler.java
  services/account/account_server-api/src/main/java/org/changppo/account/security/CustomAccessDeniedHandler.java
  services/account/account_server-api/src/main/java/org/changppo/account/security/CustomAuthenticationEntryPoint.java
  services/account/account_server-api/src/main/java/org/changppo/account/security/SecurityConfig.java
  services/account/account_server-api/src/main/java/org/changppo/account/security/oauth2/CustomLogoutSuccessHandler.java
  services/account/account_server-api/src/main/java/org/changppo/account/service/apikey/ApiKeyService.java
  services/account/account_server-api/src/main/java/org/changppo/account/service/apikey/token/TokenKeyProperties.java
  settings.gradle
  utils/jwt/build.gradle
  utils/jwt/src/main/java/org/changppo/utils/jwt/JwtProperties.java
  utils/jwt/src/main/java/org/changppo/utils/jwt/apikey/apiKeyJwtClaims.java
  utils/jwt/src/main/java/org/changppo/utils/jwt/apikey/apiKeyJwtHandler.java
  utils/response/build.gradle
  utils/response/src/main/java/org/changppo/utils/response/body/Failure.java
  utils/response/src/main/java/org/changppo/utils/response/body/Response.java
  utils/response/src/main/java/org/changppo/utils/response/body/Result.java
  utils/response/src/main/java/org/changppo/utils/response/body/Success.java
Labels: feature, refactor

#43 feat : 주요한 사용자 정보 반환 , Apikey 유효성 정보 반환, 세션 만료 정보 반환 클라이언트의 요청 구현
  services/account/account_core/account_domain/src/main/java/org/changppo/account/entity/apikey/ApiKey.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/repository/apikey/ApiKeyRepositoryImpl.java
  services/account/account_core/account_domain/src/main/java/org/changppo/account/repository/apikey/QuerydslApiKeyRepository.java
  services/account/account_server-api/src/main/java/org/changppo/account/controller/apikey/ApiKeyController.java
  services/account/account_server-api/src/main/java/org/changppo/account/controller/auth/LoginFailureController.java
  services/account/account_server-api/src/main/java/org/changppo/account/controller/member/MemberController.java
  services/account/account_server-api/src/main/java/org/changppo/account/dto/apikey/ApiKeyValidationResponse.java
  services/account/account_server-api/src/main/java/org/changppo/account/dto/member/PrincipalDto.java
  services/account/account_server-api/src/main/java/org/changppo/account/response/exception/common/ExceptionType.java
  services/account/account_server-api/src/main/java/org/changppo/account/security/SecurityConfig.java
  services/account/account_server-api/src/main/java/org/changppo/account/security/oauth2/CustomOAuth2User.java
  services/account/account_server-api/src/main/java/org/changppo/account/service/apikey/ApiKeyService.java
  services/account/account_server-api/src/main/resources/i18n/exception.properties
  services/account/account_server-api/src/test/java/org/changppo/account/controller/apikey/ApiKeyControllerIntegrationTest.java
  services/account/account_server-api/src/test/java/org/changppo/account/controller/apikey/ApiKeyControllerTest.java
  services/account/account_server-api/src/test/java/org/changppo/account/controller/member/MemberControllerIntegrationTest.java
Labels: feature, test

#48 refactor : ResponseBody 값을 역직렬화 되도록 변경
  services/account/account_server-api/build.gradle
  services/account/account_server-api/src/main/java/org/changppo/account/controller/apikey/ApiKeyController.java
  services/account/account_server-api/src/main/java/org/changppo/account/controller/auth/LoginFailureController.java
  services/account/account_server-api/src/main/java/org/changppo/account/controller/auth/LoginSuccessController.java
  services/account/account_server-api/src/main/java/org/changppo/account/controller/card/CardController.java
  services/account/account_server-api/src/main/java/org/changppo/account/controller/card/paymentgateway/kakaopay/KakaopayCardController.java
  services/account/account_server-api/src/main/java/org/changppo/account/controller/member/MemberController.java
  services/account/account_server-api/src/main/java/org/changppo/account/controller/payment/PaymentController.java
  services/account/account_server-api/src/main/java/org/changppo/account/response/exception/common/ExceptionAdvice.java
  services/account/account_server-api/src/main/java/org/changppo/account/response/exception/common/ResponseHandler.java
  services/account/account_server-api/src/main/java/org/changppo/account/security/CustomAccessDeniedHandler.java
  services/account/account_server-api/src/main/java/org/changppo/account/security/CustomAuthenticationEntryPoint.java
  services/account/account_server-api/src/main/java/org/changppo/account/security/sign/CustomLogoutSuccessHandler.java
  services/account/account_server-api/src/test/java/org/changppo/account/controller/apikey/ApiKeyControllerIntegrationTest.java
  services/account/account_server-api/src/test/java/org/changppo/account/controller/card/CardControllerIntegrationTest.java
  services/account/account_server-api/src/test/java/org/changppo/account/controller/card/paymentgateway/kakaopay/KakaopayCardControllerIntegrationTest.java
  services/account/account_server-api/src/test/java/org/changppo/account/controller/member/MemberControllerIntegrationTest.java
  services/account/account_server-api/src/test/java/org/changppo/account/controller/payment/PaymentControllerIntegrationTest.java
  utils/domain/src/main/java/org/changppo/commons/SuccessResponseBody.java
Labels: refactor

#55 fix : 기록이 존재하지 않을 때, 나타나는 버그 수정
  services/monitoring/monitoring_domain/src/main/java/org/changppo/monioring/domain/view/ApiEndpointChargeDetailsView.java
  services/monitoring/monitoring_domain/src/main/java/org/changppo/monioring/domain/view/ApiKeyChargeView.java
  services/monitoring/monitoring_domain/src/main/java/org/changppo/monioring/domain/view/DayChargeView.java
  services/monitoring/monitoring_domain/src/main/java/org/changppo/monioring/domain/view/HourChargeView.java
  services/monitoring/monitoring_domain/src/main/java/org/changppo/monioring/domain/view/MemberChargeGraphView.java
  services/monitoring/monitoring_domain/src/main/java/org/changppo/monioring/domain/view/TotalSumView.java
  services/monitoring/monitoring_server/src/main/java/org/changppo/monitoring/controller/CostQueryController.java
  services/monitoring/monitoring_server/src/main/java/org/changppo/monitoring/controller/ServerQueryController.java
  services/monitoring/monitoring_server/src/main/java/org/changppo/monitoring/service/CostQueryService.java
  services/monitoring/monitoring_server/src/main/java/org/changppo/monitoring/util/ViewFactory.java
Labels: bug

#58 devops : Spring Cloud Data Flow & Prometheus & Grafana를 이용한 모니터링 시스템 구축 #57
  services/account/account_server-api/build.gradle
  services/account/account_server-api/src/main/resources/application.yml
  services/account/account_server-batch/build.gradle
  services/account/account_server-batch/src/main/java/org/changppo/account/AccountBatchApplication.java
  services/account/account_server-batch/src/main/java/org/changppo/account/batch/config/BatchConfig.java
  services/account/account_server-batch/src/main/java/org/changppo/account/batch/config/CustomTaskConfigurer.java
  services/account/account_server-batch/src/main/java/org/changppo/account/batch/config/TaskConfig.java
  services/account/account_server-batch/src/main/java/org/changppo/account/batch/config/database/DataSourceConfig.java
  services/account/account_server-batch/src/main/resources/application-local.yml
  services/account/account_server-batch/src/main/resources/application.yml
  services/account/account_server-batch/src/main/resources/sql/batch-postgresql.sql
  services/account/docker-compose/monitoring/docker-compose.yml
  services/account/docker-compose/monitoring/prometheus/config/prometheus.yml
  services/account/docker-compose/monitoring/prometheus/config/rule.yml
Labels: devops
